! AIDC Lab — spine2
! Interfaces pre-provisioned (lo + ethN). YOUR TASK: configure BGP per docs/lab-guide/01-exercise.md
frr defaults datacenter
hostname spine2
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.0.2/32
!
interface eth1
 description to_leaf1
 ip address 10.1.2.0/31
!
interface eth2
 description to_leaf2
 ip address 10.1.2.2/31
!
interface eth3
 description to_leaf3
 ip address 10.1.2.4/31
!
interface eth4
 description to_leaf4
 ip address 10.1.2.6/31
!
line vty
!
