! AIDC Lab — leaf3
! Interfaces pre-provisioned (lo + ethN). YOUR TASK: configure BGP per docs/lab-guide/01-exercise.md
frr defaults datacenter
hostname leaf3
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.1.3/32
 ip address 10.0.10.3/32
!
interface eth1
 description to_spine1
 ip address 10.1.1.5/31
!
interface eth2
 description to_spine2
 ip address 10.1.2.5/31
!
interface eth3
 description to_gpu5
 ip address 10.2.3.0/31
!
interface eth4
 description to_gpu6
 ip address 10.2.3.2/31
!
line vty
!
