! AIDC Lab — leaf4
! Interfaces pre-provisioned (lo + ethN). YOUR TASK: configure BGP per docs/lab-guide/01-exercise.md
frr defaults datacenter
hostname leaf4
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.0.1.4/32
 ip address 10.0.10.4/32
!
interface eth1
 description to_spine1
 ip address 10.1.1.7/31
!
interface eth2
 description to_spine2
 ip address 10.1.2.7/31
!
interface eth3
 description to_gpu7
 ip address 10.2.4.0/31
!
interface eth4
 description to_gpu8
 ip address 10.2.4.2/31
!
line vty
!
